// Auto-generated by updateClassAttributes.cjs
// Original file backed up to classTemplatesLibrary.ts.1751311745742.bak
// Generated at: 2025-06-30T19:29:05.750Z

export interface ClassTemplateAttribute {
  custom_name: string;
  key: string;
  level: number;
  points: number;
  baseLevel?: number;
  user_description: string | null;
  enhancements: string[];
  limiters: string[];
  options: string[];
  user_input: string | null | Record<string, unknown>;
}

export interface ClassTemplateStat {
  stat: string;
  value: number;
  points: number;
}

export interface ClassTemplateDefect {
  custom_name: string;
  key: string;
  rank: number;
  cp_refund: number;
  user_description: string | null;
  enhancements: string[];
  limiters: string[];
  options: string[];
  user_input: string | null | Record<string, unknown>;
}

export interface ClassTemplate {
  name: string;
  template: string;
  baseSize: {
    rank: number;
    name: string;
  };
  stats: ClassTemplateStat[];
  attributes: ClassTemplateAttribute[];
  defects: ClassTemplateDefect[];
  totalPoints?: number;
  // Optional description fields for UI rendering
  description?: string;
  short_description?: string;
  // Optional image URL to display on template cards
  imageUrl?: string;
}

export interface ClassTemplatesLibrary {
  description: string;
  classes: ClassTemplate[];
}

export const CLASS_TEMPLATES_LIBRARY: ClassTemplate[] = [
  {
    "name": "ADVENTURER",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_asrai_adventurer.png",
    "stats": [],
    "attributes": [
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select 1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select 1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Gear",
        "key": "gear",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Adventuring Supplies)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring Supplies"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Melee Attack",
        "key": "melee_attack",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select Weapon Type)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select Weapon Type"
        ],
        "user_input": null
      },
      {
        "custom_name": "Melee Defence",
        "key": "melee_defence",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select Weapon Type)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select Weapon Type"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 3,
        "points": 9,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Social)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Social"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 20
  },
  {
    "name": "ARTIFICER",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_artificer.png",
    "stats": [
      {
        "stat": "Mind",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Augmented",
        "key": "augmented",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Body: tech enhancement)",
        "enhancements": [
          "Body: tech enhancement"
        ],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Multi-Gadget; 20 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Multi-Gadget",
          "20 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Power Flux",
        "key": "power_flux",
        "level": 2,
        "points": 20,
        "baseLevel": 0,
        "user_description": "(Major: Item Gadgeteer -1; Equipment: Multi-Gadget +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Major: Item Gadgeteer -1",
          "Equipment: Multi-Gadget +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Artistic)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Artistic"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Scientific)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Scientific"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 3,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Technical)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Technical"
        ],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 45
  },
  {
    "name": "BROKER",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_broker.png",
    "stats": [
      {
        "stat": "Body",
        "value": 2,
        "points": 4
      },
      {
        "stat": "Soul",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Cognition",
        "key": "cognition",
        "level": 4,
        "points": 8,
        "baseLevel": 5,
        "user_description": "(Postcognition; Equipment: Concerning Object History Only +1)",
        "enhancements": [],
        "limiters": [
          "Equipment: Concerning Object History Only +1"
        ],
        "options": [
          "Postcognition"
        ],
        "user_input": null
      },
      {
        "custom_name": "Features",
        "key": "features",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Contacts)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Contacts"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Organisational Ties",
        "key": "organisational_ties",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select One"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 3,
        "points": 9,
        "baseLevel": 0,
        "user_description": "(Business)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Business"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Social)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Social"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Technical)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Technical"
        ],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 50
  },
  {
    "name": "DEMON HUNTER",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/demon_hunter.png",
    "description": "Relentless fiend-slayers trained in many weapons and rites.",
    "stats": [
      {
        "stat": "Body",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Attack Mastery",
        "key": "attack_mastery",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "(Brutal, Concealment, Judge Opponent, Lightning Reflexes, Reflection)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Brutal",
          "Concealment",
          "Judge Opponent",
          "Lightning Reflexes",
          "Reflection"
        ],
        "user_input": null
      },
      {
        "custom_name": "Features",
        "key": "features",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Contacts: Demon Hunters)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Contacts: Demon Hunters"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Massive Damage",
        "key": "massive_damage",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Targetted: Demons +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Targetted: Demons +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Mind Shield",
        "key": "mind_shield",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Organisational Ties",
        "key": "organisational_ties",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Demon Hunters)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Demon Hunters"
        ],
        "user_input": null
      },
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select One"
        ],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Personal)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Personal"
        ],
        "user_input": null
      },
      {
        "custom_name": "Sixth Sense",
        "key": "sixth_sense",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Demons)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Demons"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Military)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Military"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Easily Distracted",
        "key": "easily_distracted",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "(Demon Lore)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Nightmares",
        "key": "nightmares",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "(Demon Attacks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 40
  },
  {
    "name": "DETECTIVE",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_detective.png",
    "stats": [
      {
        "stat": "Body",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Judge Opponent)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Judge Opponent"
        ],
        "user_input": null
      },
      {
        "custom_name": "Cognition",
        "key": "cognition",
        "level": 4,
        "points": 8,
        "baseLevel": 5,
        "user_description": "(Postcognition)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Postcognition"
        ],
        "user_input": null
      },
      {
        "custom_name": "Features",
        "key": "features",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Contacts)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Contacts"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Organisational Ties",
        "key": "organisational_ties",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select One"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Social)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Social"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Technical)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Technical"
        ],
        "user_input": null
      },
      {
        "custom_name": "Wealth",
        "key": "wealth",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 30
  },
  {
    "name": "EXORCIST",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "stats": [
      {
        "stat": "Soul",
        "value": 4,
        "points": 8
      }
    ],
    "attributes": [
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select 1)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select 1"],
        "user_input": null
      },
      {
        "custom_name": "Connected",
        "key": "connected",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select One"],
        "user_input": null
      },
      {
        "custom_name": "Energised",
        "key": "energised",
        "level": 6,
        "points": 6,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Exorcism",
        "key": "exorcism",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Mind Shield",
        "key": "mind_shield",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Academic)",
        "enhancements": [],
        "limiters": [],
        "options": ["Academic"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 2,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Detective)",
        "enhancements": [],
        "limiters": [],
        "options": ["Detective"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": ["Street"],
        "user_input": null
      },
      {
        "custom_name": "Unaffected",
        "key": "unaffected",
        "level": 3,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Select 3)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select 3"],
        "user_input": null
      },
      {
        "custom_name": "Weapon: Soul Blast",
        "key": "weapon_soul_blast",
        "level": 4,
        "points": 8,
        "baseLevel": 0,
        "user_description": "(-1 Modifier)",
        "enhancements": [],
        "limiters": ["-1 Modifier"],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Nightmares",
        "key": "nightmares",
        "rank": 1,
        "cp_refund": 1,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Wanted",
        "key": "wanted",
        "rank": 1,
        "cp_refund": 2,
        "user_description": "(Law Enforcement)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 50
  },
  {
    "name": "GATE GUARDIAN",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "stats": [
      {
        "stat": "Body",
        "value": 1,
        "points": 2
      },
      {
        "stat": "Soul",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Attack Mastery",
        "key": "attack_mastery",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Select 2)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select 2"],
        "user_input": null
      },
      {
        "custom_name": "Companion",
        "key": "companion",
        "level": 8,
        "points": 32,
        "baseLevel": 0,
        "user_description": "(Guardian Gryphon; 80 Points)",
        "enhancements": [],
        "limiters": [],
        "options": ["Guardian Gryphon", "80 Points"],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "(Various Equipment; 10 Points)",
        "enhancements": [],
        "limiters": [],
        "options": ["Various Equipment", "10 Points"],
        "user_input": null
      },
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select One"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 3,
        "points": 9,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": ["Adventuring"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Occupation: Select One)",
        "enhancements": [],
        "limiters": [],
        "options": ["Occupation: Select One"],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 60
  },
  {
    "name": "GENERAL",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "stats": [
      {
        "stat": "Body",
        "value": 1,
        "points": 2
      },
      {
        "stat": "Mind",
        "value": 2,
        "points": 4
      },
      {
        "stat": "Soul",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Companion",
        "key": "companion",
        "level": 6,
        "points": 24,
        "baseLevel": 0,
        "user_description": "(Government Agent; 60 Points)",
        "enhancements": [],
        "limiters": [],
        "options": ["Government Agent", "60 Points"],
        "user_input": null
      },
      {
        "custom_name": "Connected",
        "key": "connected",
        "level": 6,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select One"],
        "user_input": null
      },
      {
        "custom_name": "Inspire",
        "key": "inspire",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 5,
        "points": 15,
        "baseLevel": 0,
        "user_description": "(Military)",
        "enhancements": [],
        "limiters": [],
        "options": ["Military"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Social)",
        "enhancements": [],
        "limiters": [],
        "options": ["Social"],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Red Tape",
        "key": "red_tape",
        "rank": 1,
        "cp_refund": 1,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 60
  },
  {
    "name": "HACKTIVIST",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "stats": [
      {
        "stat": "Mind",
        "value": 3,
        "points": 6
      }
    ],
    "attributes": [
      {
        "custom_name": "Connected",
        "key": "connected",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select One"],
        "user_input": null
      },
      {
        "custom_name": "Data Access",
        "key": "data_access",
        "level": 5,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Enhanced: +4)",
        "enhancements": ["+4"],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Gear",
        "key": "gear",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Tech Equipment)",
        "enhancements": [],
        "limiters": [],
        "options": ["Tech Equipment"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 5,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": ["Street"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 6,
        "points": 12,
        "baseLevel": 0,
        "user_description": "(Technical)",
        "enhancements": [],
        "limiters": [],
        "options": ["Technical"],
        "user_input": null
      },
      {
        "custom_name": "Wealth",
        "key": "wealth",
        "level": 2,
        "points": 6,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 50
  },
  {
    "name": "HOT ROD",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "stats": [
      {
        "stat": "Body",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Features",
        "key": "features",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select One"],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 15,
        "points": 15,
        "baseLevel": 0,
        "user_description": "(Vehicle; 30 Points)",
        "enhancements": [],
        "limiters": [],
        "options": ["Vehicle", "30 Points"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": ["Adventuring"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "(Occupation: Driver)",
        "enhancements": [],
        "limiters": [],
        "options": ["Occupation: Driver"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Social)",
        "enhancements": [],
        "limiters": [],
        "options": ["Social"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 3,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": ["Street"],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Wanted",
        "key": "wanted",
        "rank": 1,
        "cp_refund": 2,
        "user_description": "(Law Enforcement)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 34
  },
  {
    "name": "IDOL",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "stats": [
      {
        "stat": "Soul",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Features",
        "key": "features",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Select 2)",
        "enhancements": [],
        "limiters": [],
        "options": ["Select 2"],
        "user_input": null
      },
      {
        "custom_name": "Inspire",
        "key": "inspire",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Minions",
        "key": "minions",
        "level": 3,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Assistants)",
        "enhancements": [],
        "limiters": [],
        "options": ["Assistants"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Business)",
        "enhancements": [],
        "limiters": [],
        "options": ["Business"],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Occupation: Entertainer)",
        "enhancements": [],
        "limiters": [],
        "options": ["Occupation: Entertainer"],
        "user_input": null
      },
      {
        "custom_name": "Wealth",
        "key": "wealth",
        "level": 4,
        "points": 12,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Fragile",
        "key": "fragile",
        "rank": 2,
        "cp_refund": 2,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Hounded",
        "key": "hounded",
        "rank": 2,
        "cp_refund": 4,
        "user_description": "(Fans/Media)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 1,
        "cp_refund": 1,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 1,
        "cp_refund": 1,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Reduced Damage",
        "key": "reduced_damage",
        "rank": 1,
        "cp_refund": 3,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 25
  },
  {
    "name": "MAGICAL GIRL",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_magician.png",
    "stats": [
      {
        "stat": "Soul",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Alternate Form",
        "key": "alternate_form",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Astral Projection)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Astral Projection"
        ],
        "user_input": null
      },
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select One"
        ],
        "user_input": null
      },
      {
        "custom_name": "Features",
        "key": "features",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Contacts: Magical)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Contacts: Magical"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Organisational Ties",
        "key": "organisational_ties",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Magical)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Magical"
        ],
        "user_input": null
      },
      {
        "custom_name": "Power Flux",
        "key": "power_flux",
        "level": 3,
        "points": 15,
        "baseLevel": 0,
        "user_description": "(Major: Magic)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Major: Magic"
        ],
        "user_input": null
      },
      {
        "custom_name": "Sixth Sense",
        "key": "sixth_sense",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select One Aspect)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select One Aspect"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Action: Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Action: Select One"
        ],
        "user_input": null
      },
      {
        "custom_name": "Weapon: Magical Attack",
        "key": "weapon_magical_attack",
        "level": 6,
        "points": 12,
        "baseLevel": 4,
        "user_description": "(Drain: 3 Soul)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Drain: 3 Soul"
        ],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Easily Distracted",
        "key": "easily_distracted",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "(One Trigger)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Nemesis",
        "key": "nemesis",
        "rank": 2,
        "cp_refund": 2,
        "user_description": "(One Enemy)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skeleton in the Closet",
        "key": "skeleton_in_the_closet",
        "rank": 2,
        "cp_refund": 4,
        "user_description": "(Magical Identity)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 60
  },
  {
    "name": "MARTIAL ARTIST",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_martial_artist.png",
    "stats": [
      {
        "stat": "Body",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Combat Technique",
        "key": "",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Blind Fighting, Brutal, Concealment, Deflection, Judge Opponent, Lethal Blow, Lightning Reflexes 2, Reflection, Tournament Encyclopaedia: Martial Arts)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Blind Fighting",
          "Brutal",
          "Concealment",
          "Deflection",
          "Judge Opponent",
          "Lethal Blow",
          "Lightning Reflexes 2",
          "Reflection",
          "Tournament Encyclopaedia: Martial Arts"
        ],
        "user_input": null
      },
      {
        "custom_name": "Extra Actions",
        "key": "extra_actions",
        "level": 1,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Jumping",
        "key": "jumping",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Massive Damage",
        "key": "massive_damage",
        "level": 2,
        "points": 6,
        "baseLevel": 3,
        "user_description": "(Focussed: Unarmed +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Focussed: Unarmed +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Melee Attack",
        "key": "melee_attack",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Unarmed)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Unarmed"
        ],
        "user_input": null
      },
      {
        "custom_name": "Melee Defence",
        "key": "melee_defence",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Unarmed)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Unarmed"
        ],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Personal)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Personal"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 2,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      },
      {
        "custom_name": "Tough",
        "key": "tough",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weapon: Finishing Move",
        "key": "weapon_finishing_move",
        "level": 3,
        "points": 6,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weapon: Ki Blast",
        "key": "weapon_ki_blast",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Drain: Body -1; Enervation -1; Range -1; Backblast +2; Hands +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Drain: Body -1",
          "Enervation -1",
          "Range -1",
          "Backblast +2",
          "Hands +1"
        ],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 60
  },
  {
    "name": "MASTER THIEF",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_faery_master_thief.png",
    "stats": [
      {
        "stat": "Body",
        "value": 1,
        "points": 2
      },
      {
        "stat": "Mind",
        "value": 1,
        "points": 2
      },
      {
        "stat": "Soul",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Features",
        "key": "features",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Ambidexterity, Appearance, Eidetic Memory)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Ambidexterity",
          "Appearance",
          "Eidetic Memory"
        ],
        "user_input": null
      },
      {
        "custom_name": "Gear",
        "key": "gear",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Thieving Supplies)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Thieving Supplies"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Mulligan",
        "key": "mulligan",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Academic)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Academic"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "(Occupation: Thief)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Occupation: Thief"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 3,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Social)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Social"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 3,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Technical)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Technical"
        ],
        "user_input": null
      },
      {
        "custom_name": "Wealth",
        "key": "wealth",
        "level": 3,
        "points": 9,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Nemesis",
        "key": "nemesis",
        "rank": 2,
        "cp_refund": 2,
        "user_description": "(One Enemy)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Wanted",
        "key": "wanted",
        "rank": 2,
        "cp_refund": 4,
        "user_description": "(Law Enforcement)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 50
  },
  {
    "name": "MECHA PILOT",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_mech_pilot.png",
    "stats": [],
    "attributes": [
      {
        "custom_name": "Attack Mastery",
        "key": "attack_mastery",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Connected",
        "key": "connected",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select One"
        ],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 30,
        "points": 30,
        "baseLevel": 0,
        "user_description": "(Mecha and Equipment; 60 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Mecha and Equipment",
          "60 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Massive Damage",
        "key": "massive_damage",
        "level": 2,
        "points": 6,
        "baseLevel": 3,
        "user_description": "(Focussed: Mecha Weapons +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Focussed: Mecha Weapons +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Mecha Weapons)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Mecha Weapons"
        ],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Mecha Movement)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Mecha Movement"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Military)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Military"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Occupation: Mecha Pilot)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Occupation: Mecha Pilot"
        ],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 50
  },
  {
    "name": "MERCENARY",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_yueri_mercenary.png",
    "stats": [
      {
        "stat": "Body",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Attack Mastery",
        "key": "attack_mastery",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Weapons Encyclopaedia + Select 3 Others)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Weapons Encyclopaedia + Select 3 Others"
        ],
        "user_input": null
      },
      {
        "custom_name": "Defence Mastery",
        "key": "defence_mastery",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Gear",
        "key": "gear",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Various Weapons and Equipment)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Various Weapons and Equipment"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 2,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Business)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Business"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Military)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Military"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Social)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Social"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Technical)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Technical"
        ],
        "user_input": null
      },
      {
        "custom_name": "Wealth",
        "key": "wealth",
        "level": 3,
        "points": 9,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 45
  },
  {
    "name": "NINJA",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_grey_ninja.png",
    "stats": [
      {
        "stat": "Body",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Attack Mastery",
        "key": "attack_mastery",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 8,
        "points": 8,
        "baseLevel": 0,
        "user_description": "(Blind Fighting, Blind Shooting, Brutal, Concealment, Lethal Blow, Lightning Reflexes 2, Portable Armoury)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Blind Fighting",
          "Blind Shooting",
          "Brutal",
          "Concealment",
          "Lethal Blow",
          "Lightning Reflexes 2",
          "Portable Armoury"
        ],
        "user_input": null
      },
      {
        "custom_name": "Defence Mastery",
        "key": "defence_mastery",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Dynamic Powers",
        "key": "dynamic_powers",
        "level": 1,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Ninja Tricks)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Ninja Tricks"
        ],
        "user_input": null
      },
      {
        "custom_name": "Gear",
        "key": "gear",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Ninja Supplies)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Ninja Supplies"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Weapons; 20 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Weapons",
          "20 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Jumping",
        "key": "jumping",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Massive Damage",
        "key": "massive_damage",
        "level": 2,
        "points": 6,
        "baseLevel": 3,
        "user_description": "(Focussed: Unarmed +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Focussed: Unarmed +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 3,
        "points": 9,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Artistic)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Artistic"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 6,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Balance, Cat-Like, Fast, Light-Footed, Untrackable, Wall-Bouncing)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Balance",
          "Cat-Like",
          "Fast",
          "Light-Footed",
          "Untrackable",
          "Wall-Bouncing"
        ],
        "user_input": null
      },
      {
        "custom_name": "Tough",
        "key": "tough",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 70
  },
  {
    "name": "PET MONSTER TRAINER",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_dwarf_pet_monster_trainer.png",
    "stats": [
      {
        "stat": "Soul",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Tournament Encyclopaedia: Pet Monster Duels)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Tournament Encyclopaedia: Pet Monster Duels"
        ],
        "user_input": null
      },
      {
        "custom_name": "Companion",
        "key": "companion",
        "level": 2,
        "points": 8,
        "baseLevel": 0,
        "user_description": "(Novice Pet Monster; 20 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Novice Pet Monster",
          "20 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Companion",
        "key": "companion",
        "level": 4,
        "points": 16,
        "baseLevel": 0,
        "user_description": "(Veteran Pet Monster; 40 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Veteran Pet Monster",
          "40 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Inspire",
        "key": "inspire",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Occupation: Pet Monster Trainer)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Occupation: Pet Monster Trainer"
        ],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Nemesis",
        "key": "",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "(One Rival)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 30
  },
  {
    "name": "PIRATE",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_half_dragon_pirate.png",
    "stats": [
      {
        "stat": "Body",
        "value": 1,
        "points": 2
      }
    ],
    "attributes": [
      {
        "custom_name": "Attack Mastery",
        "key": "attack_mastery",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Defence Mastery",
        "key": "defence_mastery",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Enemy Attack",
        "key": "enemy_attack",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select Enemy)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select Enemy"
        ],
        "user_input": null
      },
      {
        "custom_name": "Features",
        "key": "features",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Appearance)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Appearance"
        ],
        "user_input": null
      },
      {
        "custom_name": "Inspire",
        "key": "inspire",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "(Various Equipment; 10 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Various Equipment",
          "10 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Mulligan",
        "key": "mulligan",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 3,
        "points": 9,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 3,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Easily Distracted",
        "key": "easily_distracted",
        "rank": 2,
        "cp_refund": 2,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Marked",
        "key": "marked",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Nemesis",
        "key": "nemesis",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Wanted",
        "key": "wanted",
        "rank": 1,
        "cp_refund": 2,
        "user_description": "(Law Enforcement)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 25
  },
  {
    "name": "SAMURAI",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_grey_samurai.png",
    "stats": [
      {
        "stat": "Body",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Blind Fighting, Judge Opponent, Lethal Blow, Lightning Reflexes)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Blind Fighting",
          "Judge Opponent",
          "Lethal Blow",
          "Lightning Reflexes"
        ],
        "user_input": null
      },
      {
        "custom_name": "Extra Actions",
        "key": "extra_actions",
        "level": 1,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Gear",
        "key": "gear",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Family Heirlooms)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Family Heirlooms"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inspire",
        "key": "inspire",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Weapons; 20 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Weapons",
          "20 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Massive Damage",
        "key": "massive_damage",
        "level": 3,
        "points": 9,
        "baseLevel": 4,
        "user_description": "(Focussed: Sword +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Focussed: Sword +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Melee Attack",
        "key": "melee_attack",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Sword)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Sword"
        ],
        "user_input": null
      },
      {
        "custom_name": "Melee Defence",
        "key": "melee_defence",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Sword)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Sword"
        ],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Personal)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Personal"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 2,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Artistic)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Artistic"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Domestic)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Domestic"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "(Social)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Social"
        ],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Zen Direction)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Zen Direction"
        ],
        "user_input": null
      },
      {
        "custom_name": "Tough",
        "key": "tough",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Social Fault",
        "key": "social_fault",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "(Bushido Code)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 65
  },
  {
    "name": "SENTAI MEMBER",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_sentai_member.png",
    "stats": [
      {
        "stat": "Body",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Attack Mastery",
        "key": "attack_mastery",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Environmental: Near Teammates +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Environmental: Near Teammates +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Defence Mastery",
        "key": "defence_mastery",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Environmental: Near Teammates +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Environmental: Near Teammates +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Pool of Shared Mecha Equipment; 20 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Pool of Shared Mecha Equipment",
          "20 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Massive Damage",
        "key": "massive_damage",
        "level": 1,
        "points": 3,
        "baseLevel": 3,
        "user_description": "(Environmental: Near Teammates +1; Focussed: Choose Weapon +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Environmental: Near Teammates +1",
          "Focussed: Choose Weapon +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Mulligan",
        "key": "mulligan",
        "level": 2,
        "points": 2,
        "baseLevel": 3,
        "user_description": "(Environmental: Near Teammates +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Environmental: Near Teammates +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Sixth Sense",
        "key": "sixth_sense",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Danger to Teammates)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Danger to Teammates"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 1,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Weapon: Combined Attack",
        "key": "weapon",
        "level": 5,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Assisted: Teammates",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 35
  },
  {
    "name": "SHADOW WARRIOR",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/yurei_shadow_warrior.png",
    "stats": [
      {
        "stat": "Body",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Change State",
        "key": "change_state",
        "level": 5,
        "points": 15,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Immutable",
        "key": "immutable",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Weapons; 20 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Weapons",
          "20 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Massive Damage",
        "key": "massive_damage",
        "level": 5,
        "points": 15,
        "baseLevel": 6,
        "user_description": "(Focussed: Sword +1)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Focussed: Sword +1"
        ],
        "user_input": null
      },
      {
        "custom_name": "Melee Attack",
        "key": "melee_attack",
        "level": 6,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Sword)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Sword"
        ],
        "user_input": null
      },
      {
        "custom_name": "Melee Defence",
        "key": "melee_defence",
        "level": 6,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Sword)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Sword"
        ],
        "user_input": null
      },
      {
        "custom_name": "Regeneration",
        "key": "regeneration",
        "level": 2,
        "points": 10,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Street)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Street"
        ],
        "user_input": null
      },
      {
        "custom_name": "Tough",
        "key": "tough",
        "level": 6,
        "points": 6,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 75
  },
  {
    "name": "STUDENT",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_dark_elf_student.png",
    "stats": [
      {
        "stat": "Soul",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Connected",
        "key": "connected",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Select One)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Select One"
        ],
        "user_input": null
      },
      {
        "custom_name": "Energised",
        "key": "energised",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Features",
        "key": "features",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "(Animal Empathy)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Animal Empathy"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Awareness",
        "key": "heightened_awareness",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Mulligan",
        "key": "mulligan",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_background",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Occupation: Student)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Occupation: Student"
        ],
        "user_input": null
      },
      {
        "custom_name": "Unknown Power",
        "key": "unknown_power",
        "level": 20,
        "points": 20,
        "baseLevel": 0,
        "user_description": "(30 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "30 Points"
        ],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Magnet",
        "key": "magnet",
        "rank": 1,
        "cp_refund": 1,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 35
  },
  {
    "name": "TECH GENIUS",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_android_battle_maid_tech_genius2.png",
    "stats": [
      {
        "stat": "Mind",
        "value": 2,
        "points": 4
      }
    ],
    "attributes": [
      {
        "custom_name": "Gear",
        "key": "gear",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "(Various Equipment)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Various Equipment"
        ],
        "user_input": null
      },
      {
        "custom_name": "Features",
        "key": "features",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Eidetic Memory, Lightning Calculator, Speed Reading)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Eidetic Memory",
          "Lightning Calculator",
          "Speed Reading"
        ],
        "user_input": null
      },
      {
        "custom_name": "Item",
        "key": "item",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Powerful Gadgets; 20 Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Powerful Gadgets",
          "20 Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Power Flux",
        "key": "power_flux",
        "level": 2,
        "points": 20,
        "baseLevel": 6,
        "user_description": "(Primal: Super Inventor -2; Activation +3; Equipment: Workshop +3)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Primal: Super Inventor -2",
          "Activation +3",
          "Equipment: Workshop +3"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Business)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Business"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_field",
        "level": 6,
        "points": 12,
        "baseLevel": 0,
        "user_description": "(Technical)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Technical"
        ],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 55
  },
  {
    "name": "WARDER",
    "template": "class",
    "baseSize": {
      "rank": 0,
      "name": "Medium"
    },
    "imageUrl": "/images/profile_giant_living_robot_warder.png",
    "stats": [],
    "attributes": [
      {
        "custom_name": "Absorption",
        "key": "absorption",
        "level": 2,
        "points": 10,
        "baseLevel": 0,
        "user_description": "(Health Points)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Health Points"
        ],
        "user_input": null
      },
      {
        "custom_name": "Augmented",
        "key": "augmented",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Body Stat; Source: Ward Magic)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Body Stat",
          "Source: Ward Magic"
        ],
        "user_input": null
      },
      {
        "custom_name": "Combat Technique",
        "key": "combat_technique",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Brutal; Lethal Blow)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Brutal",
          "Lethal Blow"
        ],
        "user_input": null
      },
      {
        "custom_name": "Heightened Senses",
        "key": "heightened_senses",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Hearing, Smell, Vision)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Hearing",
          "Smell",
          "Vision"
        ],
        "user_input": null
      },
      {
        "custom_name": "Immutable",
        "key": "immutable",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Melee Attack",
        "key": "melee_attack",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "(Unarmed)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Unarmed"
        ],
        "user_input": null
      },
      {
        "custom_name": "Melee Defence",
        "key": "melee_defence",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "(Unarmed)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Unarmed"
        ],
        "user_input": null
      },
      {
        "custom_name": "Power Flux",
        "key": "power_flux",
        "level": 2,
        "points": 20,
        "baseLevel": 4,
        "user_description": "(Major: Combat; Activation: Wards; Unique Limiter: No Fluxing Attributes of Wards)",
        "enhancements": [],
        "limiters": [
          "Unique Limiter: No Fluxing Attributes of Wards"
        ],
        "options": [
          "Major: Combat",
          "Activation: Wards"
        ],
        "user_input": null
      },
      {
        "custom_name": "Skill Group",
        "key": "skill_group_action",
        "level": 2,
        "points": 6,
        "baseLevel": 0,
        "user_description": "(Adventuring)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Adventuring"
        ],
        "user_input": null
      },
      {
        "custom_name": "Transfer",
        "key": "transfer",
        "level": 2,
        "points": 6,
        "baseLevel": 4,
        "user_description": "(Specific Attribute: Power Flux +2)",
        "enhancements": [],
        "limiters": [],
        "options": [
          "Specific Attribute: Power Flux +2"
        ],
        "user_input": null
      },
      {
        "custom_name": "Tough",
        "key": "tough",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Marked",
        "key": "marked",
        "rank": 3,
        "cp_refund": 3,
        "user_description": "(Whole Body)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 60
  }
];

// Utility functions
export function getClassTemplateByName(name: string): ClassTemplate | undefined {
  return CLASS_TEMPLATES_LIBRARY.find(cls => cls.name === name);
}

export function getClassTemplateByKey(key: string): ClassTemplate | undefined {
  return CLASS_TEMPLATES_LIBRARY.find(cls => 
    cls.name.toLowerCase().replace(/\s+/g, '-') === key.toLowerCase()
  );
}

export function searchClassTemplates(query: string): ClassTemplate[] {
  const searchTerm = query.toLowerCase();
  return CLASS_TEMPLATES_LIBRARY.filter(cls => 
    cls.name.toLowerCase().includes(searchTerm) ||
    cls.attributes.some(attr => 
      (attr.custom_name || '').toLowerCase().includes(searchTerm) ||
      (attr.user_description || '').toLowerCase().includes(searchTerm)
    )
  );
}

export function getAllClassTemplates(): ClassTemplate[] {
  return [...CLASS_TEMPLATES_LIBRARY];
}