// Auto-generated by normalizeSizeTemplates.cjs
// Original file backed up to sizeTemplatesLibrary.ts.1751312529718.bak
// Generated at: 2025-06-30T19:42:09.729Z

export interface SizeTemplateAttribute {
  custom_name: string;
  key: string;
  level: number;
  points: number;
  baseLevel?: number;
  user_description: string | null;
  enhancements: string[];
  limiters: string[];
  options: string[];
  user_input: string | null | Record<string, unknown>;
}

export interface SizeTemplateDefect {
  custom_name: string;
  key: string;
  rank: number;
  cp_refund: number;
  user_description: string | null;
  enhancements: string[];
  limiters: string[];
  options: string[];
  user_input: string | null | Record<string, unknown>;
}

export interface SizeModifiers {
  liftingCapacity: string;
  strengthDamage: string;
  armourEffect: string;
  rangedModifier: string;
  speedRangeMultiplier: string;
}

export interface SizeTemplate {
  name: string;
  key: string;
  template: string;
  rank: number;
  typicalHeight: string;
  typicalMass: string;
  modifiers: SizeModifiers;
  attributes: SizeTemplateAttribute[];
  defects: SizeTemplateDefect[];
  totalPoints?: number;
  // Optional description fields for UI rendering
  description?: string;
  short_description?: string;
}

export interface SizeTemplatesLibrary {
  description: string;
  sizes: SizeTemplate[];
}

export const SIZE_TEMPLATES_LIBRARY: SizeTemplate[] = [
  {
    "name": "Point",
    "key": "point",
    "template": "size",
    "rank": -10,
    "typicalHeight": "100-400 µm",
    "typicalMass": "1-40 µg",
    "modifiers": {
      "liftingCapacity": "÷ 5 M",
      "strengthDamage": "-100",
      "armourEffect": "+100 damage",
      "rangedModifier": "+20",
      "speedRangeMultiplier": "÷ 1,000"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 10,
        "points": 20,
        "baseLevel": 0,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 10,
        "cp_refund": 138,
        "user_description": "Lifting Capacity ÷5 (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 10,
        "cp_refund": 10,
        "user_description": "Running Speed ÷1024",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 10,
        "cp_refund": 20,
        "user_description": "-100 Strength Damage",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 10,
        "cp_refund": 40,
        "user_description": "Suffers 100 Extra Damage from all Attacks",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 10,
        "cp_refund": 10,
        "user_description": "Thrown weapon distance ÷1024",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -158
  },
  {
    "name": "Mote",
    "key": "mote",
    "template": "size",
    "rank": -9,
    "typicalHeight": "500-900 µm",
    "typicalMass": "50-500 µg",
    "modifiers": {
      "liftingCapacity": "÷ 1 M",
      "strengthDamage": "-90",
      "armourEffect": "+90 damage",
      "rangedModifier": "+18",
      "speedRangeMultiplier": "÷ 500"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 9,
        "points": 9,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 9,
        "points": 9,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 9,
        "points": 18,
        "baseLevel": 0,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 9,
        "cp_refund": 54,
        "user_description": "Lifting Capacity ÷5 (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 9,
        "cp_refund": 9,
        "user_description": "Running Speed ÷512",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 9,
        "cp_refund": 18,
        "user_description": "-90 Strength Damage",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 9,
        "cp_refund": 36,
        "user_description": "Suffers 90 Extra Damage from all Attacks",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 9,
        "cp_refund": 9,
        "user_description": "Thrown weapon distance ÷512",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -80
  },
  {
    "name": "Speck",
    "key": "speck",
    "template": "size",
    "rank": -8,
    "typicalHeight": "1-4 mm",
    "typicalMass": "1-5mg",
    "modifiers": {
      "liftingCapacity": "÷ 250 k",
      "strengthDamage": "-80",
      "armourEffect": "+80 damage",
      "rangedModifier": "+16",
      "speedRangeMultiplier": "÷ 250"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 8,
        "points": 8,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 8,
        "points": 8,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 8,
        "points": 16,
        "baseLevel": 0,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 8,
        "cp_refund": 48,
        "user_description": "Lifting Capacity ÷5 (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 8,
        "cp_refund": 8,
        "user_description": "Running Speed ÷256",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 8,
        "cp_refund": 16,
        "user_description": "-80 Strength Damage",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 8,
        "cp_refund": 32,
        "user_description": "Suffers 80 Extra Damage from all Attacks",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 8,
        "cp_refund": 8,
        "user_description": "Thrown weapon distance ÷256",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -64
  },
  {
    "name": "Minute",
    "key": "minute",
    "template": "size",
    "rank": -7,
    "typicalHeight": "5-9 mm",
    "typicalMass": "6-40 mg",
    "modifiers": {
      "liftingCapacity": "÷ 50 k",
      "strengthDamage": "-70",
      "armourEffect": "+70 damage",
      "rangedModifier": "+14",
      "speedRangeMultiplier": "÷ 125"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 7,
        "points": 7,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 7,
        "points": 7,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 7,
        "points": 14,
        "baseLevel": 0,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 7,
        "cp_refund": 42,
        "user_description": "Lifting Capacity ÷5 (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 7,
        "cp_refund": 14,
        "user_description": "-10 Strength Damage (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 7,
        "cp_refund": 28,
        "user_description": "Suffers 10 Extra Damage from all Attacks (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 7,
        "cp_refund": 7,
        "user_description": "Thrown weapon distance ÷128",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 7,
        "cp_refund": 7,
        "user_description": "Running Speed ÷128",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -50
  },
  {
    "name": "Wee",
    "key": "wee",
    "template": "size",
    "rank": -6,
    "typicalHeight": "1-2 cm",
    "typicalMass": "50-500 mg",
    "modifiers": {
      "liftingCapacity": "÷ 10 k",
      "strengthDamage": "-60",
      "armourEffect": "+60 damage",
      "rangedModifier": "+12",
      "speedRangeMultiplier": "÷ 60"
    },
    "attributes": [],
    "defects": [],
    "totalPoints": -40
  },
  {
    "name": "Teeny",
    "key": "teeny",
    "template": "size",
    "rank": -5,
    "typicalHeight": "3-4 cm",
    "typicalMass": "1-5 g",
    "modifiers": {
      "liftingCapacity": "÷ 2.5 k",
      "strengthDamage": "-50",
      "armourEffect": "+50 damage",
      "rangedModifier": "+10",
      "speedRangeMultiplier": "÷ 30"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 5,
        "points": 10,
        "baseLevel": 0,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 5,
        "cp_refund": 30,
        "user_description": "Lifting Capacity ÷5 (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 5,
        "cp_refund": 5,
        "user_description": "Running Speed ÷32",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 5,
        "cp_refund": 10,
        "user_description": "-50 Strength Damage",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 5,
        "cp_refund": 20,
        "user_description": "Suffers 50 Extra Damage from all Attacks",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 5,
        "cp_refund": 5,
        "user_description": "Thrown weapon distance ÷32",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -30
  },
  {
    "name": "Fine",
    "key": "fine",
    "template": "size",
    "rank": -4,
    "typicalHeight": "5-9 cm",
    "typicalMass": "6-30 g",
    "modifiers": {
      "liftingCapacity": "÷ 500",
      "strengthDamage": "-40",
      "armourEffect": "+40 damage",
      "rangedModifier": "+8",
      "speedRangeMultiplier": "÷ 15"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 4,
        "points": 8,
        "baseLevel": 0,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 4,
        "cp_refund": 24,
        "user_description": "Lifting Capacity ÷5 (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 4,
        "cp_refund": 4,
        "user_description": "Running Speed ÷16",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 4,
        "cp_refund": 8,
        "user_description": "-40 Strength Damage",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 4,
        "cp_refund": 16,
        "user_description": "Suffers 40 Extra Damage from all Attacks",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 4,
        "cp_refund": 4,
        "user_description": "Thrown weapon distance ÷16",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -24
  },
  {
    "name": "Diminutive",
    "key": "diminutive",
    "template": "size",
    "rank": -3,
    "typicalHeight": "10-24 cm",
    "typicalMass": "50-300 g",
    "modifiers": {
      "liftingCapacity": "÷ 100",
      "strengthDamage": "-30",
      "armourEffect": "+30 damage",
      "rangedModifier": "+6",
      "speedRangeMultiplier": "÷ 8"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 3,
        "points": 3,
        "baseLevel": 3,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 3,
        "points": 3,
        "baseLevel": 3,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 3,
        "points": 6,
        "baseLevel": 3,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 3,
        "cp_refund": 18,
        "user_description": "Lifting Capacity ÷100",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 3,
        "cp_refund": 6,
        "user_description": "-30 Strength Damage",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 3,
        "cp_refund": 12,
        "user_description": "Suffers 30 Extra Damage from all Attacks",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 3,
        "cp_refund": 3,
        "user_description": "Thrown weapon distance ÷8",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 3,
        "cp_refund": 3,
        "user_description": "Running Speed ÷8",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -18
  },
  {
    "name": "Tiny",
    "key": "tiny",
    "template": "size",
    "rank": -2,
    "typicalHeight": "25-49 cm",
    "typicalMass": "500 g - 2 kg",
    "modifiers": {
      "liftingCapacity": "÷ 25",
      "strengthDamage": "-20",
      "armourEffect": "+20 damage",
      "rangedModifier": "+4",
      "speedRangeMultiplier": "÷ 4"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 2,
        "cp_refund": 12,
        "user_description": "Lifting Capacity ÷25",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 2,
        "cp_refund": 2,
        "user_description": "Running Speed ÷4",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 2,
        "cp_refund": 4,
        "user_description": "-20 Strength Damage",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 2,
        "cp_refund": 8,
        "user_description": "Suffers 20 Extra Damage from all Attacks",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 2,
        "cp_refund": 2,
        "user_description": "Thrown weapon distance ÷4",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -20
  },
  {
    "name": "Small",
    "key": "small",
    "template": "size",
    "rank": -1,
    "typicalHeight": "50-99 cm",
    "typicalMass": "6-20 kg",
    "modifiers": {
      "liftingCapacity": "÷ 5",
      "strengthDamage": "-10",
      "armourEffect": "+10 damage",
      "rangedModifier": "+2",
      "speedRangeMultiplier": "÷ 2"
    },
    "attributes": [
      {
        "custom_name": "Ranged Attack",
        "key": "ranged_attack",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Ranged Defence",
        "key": "ranged_defence",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "All",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 1,
        "points": 2,
        "baseLevel": 0,
        "user_description": "Small, Light, and Unobtrusive",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Lifting Capacity",
        "key": "unique_defect",
        "rank": 1,
        "cp_refund": 6,
        "user_description": "Lifting Capacity ÷5",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Strength Damage",
        "key": "unique_defect",
        "rank": 1,
        "cp_refund": 2,
        "user_description": "-10 Strength Damage",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Vulnerable",
        "key": "unique_defect",
        "rank": 1,
        "cp_refund": 4,
        "user_description": "Suffers 10 Extra Damage from all Attacks",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Weak Throw",
        "key": "unique_defect",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "Thrown weapon distance ÷2",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Running Speed",
        "key": "unique_defect",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "Running Speed ÷2",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": -6
  },
  {
    "name": "Medium",
    "key": "medium",
    "template": "size",
    "rank": 0,
    "typicalHeight": "1-2 m",
    "typicalMass": "50 - 150 kg",
    "modifiers": {
      "liftingCapacity": "—",
      "strengthDamage": "—",
      "armourEffect": "—",
      "rangedModifier": "—",
      "speedRangeMultiplier": "—"
    },
    "attributes": [],
    "defects": [],
    "totalPoints": 0
  },
  {
    "name": "Large",
    "key": "large",
    "template": "size",
    "rank": 1,
    "typicalHeight": "3-4 m",
    "typicalMass": "200 - 1,200 kg",
    "modifiers": {
      "liftingCapacity": "x 5",
      "strengthDamage": "+10",
      "armourEffect": "+10 AR",
      "rangedModifier": "-2",
      "speedRangeMultiplier": "x 2"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 2,
        "points": 8,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 2,
        "points": 4,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 1,
        "points": 1,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 1,
        "cp_refund": 2,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 1,
        "cp_refund": 1,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 10
  },
  {
    "name": "Huge",
    "key": "huge",
    "template": "size",
    "rank": 2,
    "typicalHeight": "5-8 m",
    "typicalMass": "1.5 - 8 tonnes",
    "modifiers": {
      "liftingCapacity": "x 25",
      "strengthDamage": "+20",
      "armourEffect": "+20 AR",
      "rangedModifier": "-4",
      "speedRangeMultiplier": "x 4"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 4,
        "points": 16,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 4,
        "points": 8,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 2,
        "points": 2,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 2,
        "cp_refund": 4,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 2,
        "cp_refund": 2,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 2,
        "cp_refund": 2,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 20
  },
  {
    "name": "Mammoth",
    "key": "mammoth",
    "template": "size",
    "rank": 3,
    "typicalHeight": "9-15 m",
    "typicalMass": "10 - 60 tonnes",
    "modifiers": {
      "liftingCapacity": "x 100",
      "strengthDamage": "+30",
      "armourEffect": "+30 AR",
      "rangedModifier": "-6",
      "speedRangeMultiplier": "x 8"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 6,
        "points": 24,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 6,
        "points": 12,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 3,
        "points": 3,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 3,
        "cp_refund": 6,
        "user_description": "Big, Heavy, and Obvious",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 3,
        "cp_refund": 3,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 3,
        "cp_refund": 3,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 30
  },
  {
    "name": "Gigantic",
    "key": "gigantic",
    "template": "size",
    "rank": 4,
    "typicalHeight": "16-30 m",
    "typicalMass": "75 - 500 tonnes",
    "modifiers": {
      "liftingCapacity": "x 500",
      "strengthDamage": "+40",
      "armourEffect": "+40 AR",
      "rangedModifier": "-8",
      "speedRangeMultiplier": "x 15"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 8,
        "points": 32,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 8,
        "points": 16,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 4,
        "points": 4,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 4,
        "cp_refund": 8,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 4,
        "cp_refund": 4,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 4,
        "cp_refund": 4,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 40
  },
  {
    "name": "Gargantuan",
    "key": "gargantuan",
    "template": "size",
    "rank": 5,
    "typicalHeight": "31-60 m",
    "typicalMass": "550 - 4,000 tonnes",
    "modifiers": {
      "liftingCapacity": "x 2.5 k",
      "strengthDamage": "+50",
      "armourEffect": "+50 AR",
      "rangedModifier": "-10",
      "speedRangeMultiplier": "x 30"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 10,
        "points": 40,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 10,
        "points": 20,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 5,
        "points": 5,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [],
    "totalPoints": 50
  },
  {
    "name": "Colossal",
    "key": "colossal",
    "template": "size",
    "rank": 6,
    "typicalHeight": "61-125 m",
    "typicalMass": "4 k - 30 k tonnes",
    "modifiers": {
      "liftingCapacity": "x 10 k",
      "strengthDamage": "+60",
      "armourEffect": "+60 AR",
      "rangedModifier": "-12",
      "speedRangeMultiplier": "x 60"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 12,
        "points": 48,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 12,
        "points": 24,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 6,
        "points": 6,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 6,
        "points": 6,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 6,
        "cp_refund": 12,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 6,
        "cp_refund": 6,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 6,
        "cp_refund": 6,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 60
  },
  {
    "name": "Enormous",
    "key": "enormous",
    "template": "size",
    "rank": 7,
    "typicalHeight": "126-250 m",
    "typicalMass": "40 k - 250 k tonnes",
    "modifiers": {
      "liftingCapacity": "x 50 k",
      "strengthDamage": "+70",
      "armourEffect": "+70 AR",
      "rangedModifier": "-14",
      "speedRangeMultiplier": "x 125"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 14,
        "points": 56,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 14,
        "points": 28,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 7,
        "points": 7,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 7,
        "points": 7,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 7,
        "cp_refund": 14,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 7,
        "cp_refund": 7,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 7,
        "cp_refund": 7,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 70
  },
  {
    "name": "Monstrous",
    "key": "monstrous",
    "template": "size",
    "rank": 8,
    "typicalHeight": "251-500 m",
    "typicalMass": "300 k - 2 M tonnes",
    "modifiers": {
      "liftingCapacity": "x 250 k",
      "strengthDamage": "+80",
      "armourEffect": "+80 AR",
      "rangedModifier": "-16",
      "speedRangeMultiplier": "x 250"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 16,
        "points": 64,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 16,
        "points": 32,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 8,
        "points": 8,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 8,
        "points": 8,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 8,
        "cp_refund": 16,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 8,
        "cp_refund": 8,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 8,
        "cp_refund": 8,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 80
  },
  {
    "name": "Titanic",
    "key": "titanic",
    "template": "size",
    "rank": 9,
    "typicalHeight": "500-1,000 m",
    "typicalMass": "2 M - 15 M tonnes",
    "modifiers": {
      "liftingCapacity": "x 1 M",
      "strengthDamage": "+90",
      "armourEffect": "+90 AR",
      "rangedModifier": "-18",
      "speedRangeMultiplier": "x 500"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 18,
        "points": 72,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 18,
        "points": 36,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 9,
        "points": 9,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 9,
        "points": 9,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 9,
        "cp_refund": 18,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 9,
        "cp_refund": 9,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 9,
        "cp_refund": 9,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 90
  },
  {
    "name": "Monumental",
    "key": "monumental",
    "template": "size",
    "rank": 10,
    "typicalHeight": "1-2 km",
    "typicalMass": "15 M - 125 M tonnes",
    "modifiers": {
      "liftingCapacity": "x 5 M",
      "strengthDamage": "+100",
      "armourEffect": "+100 AR",
      "rangedModifier": "-20",
      "speedRangeMultiplier": "x 1,000"
    },
    "attributes": [
      {
        "custom_name": "Superstrength",
        "key": "superstrength",
        "level": 20,
        "points": 80,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Armour",
        "key": "armour",
        "level": 20,
        "points": 40,
        "baseLevel": 0,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Special Movement",
        "key": "special_movement",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "Fast",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Unique Attribute",
        "key": "unique_attribute",
        "level": 10,
        "points": 10,
        "baseLevel": 0,
        "user_description": "x2 Thrown Weapon Distance (Multiple Ranks)",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "defects": [
      {
        "custom_name": "Big, Heavy, and Obvious",
        "key": "unique_defect",
        "rank": 10,
        "cp_refund": 20,
        "user_description": null,
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Attack",
        "key": "inept_attack",
        "rank": 10,
        "cp_refund": 10,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      },
      {
        "custom_name": "Inept Defence",
        "key": "inept_defence",
        "rank": 10,
        "cp_refund": 10,
        "user_description": "Ranged",
        "enhancements": [],
        "limiters": [],
        "options": [],
        "user_input": null
      }
    ],
    "totalPoints": 100
  }
];

// Utility functions
export function getSizeTemplateByName(name: string): SizeTemplate | undefined {
  return SIZE_TEMPLATES_LIBRARY.find(size => size.name === name);
}

export function getSizeTemplateByKey(key: string): SizeTemplate | undefined {
  return SIZE_TEMPLATES_LIBRARY.find(size => size.key === key);
}

export function getSizeTemplateByRank(rank: number): SizeTemplate | undefined {
  return SIZE_TEMPLATES_LIBRARY.find(size => size.rank === rank);
}

export function searchSizeTemplates(query: string): SizeTemplate[] {
  const searchTerm = query.toLowerCase();
  return SIZE_TEMPLATES_LIBRARY.filter(size => 
    size.name.toLowerCase().includes(searchTerm) ||
    size.attributes.some(attr => 
      (attr.custom_name || '').toLowerCase().includes(searchTerm) ||
      (attr.user_description || '').toLowerCase().includes(searchTerm)
    )
  );
}

export function getAllSizeTemplates(): SizeTemplate[] {
  return [...SIZE_TEMPLATES_LIBRARY];
}

export function getSizeTemplatesByRankRange(minRank: number, maxRank: number): SizeTemplate[] {
  return SIZE_TEMPLATES_LIBRARY.filter(size => 
    size.rank >= minRank && size.rank <= maxRank
  ).sort((a, b) => a.rank - b.rank);
}